export const SEASON_DETAILS_REQUEST = "SEASON_DETAILS_REQUEST";
export const SEASON_DETAILS_SUCCESS = "SEASON_DETAILS_SUCCESS";
export const SEASON_DETAILS_FAIL = "SEASON_DETAILS_FAIL";

export const SEASON_UPDATE_REQUEST = "SEASON_UPDATE_REQUEST";
export const SEASON_UPDATE_SUCCESS = "SEASON_UPDATE_SUCCESS";
export const SEASON_UPDATE_FAIL = "SEASON_UPDATE_FAIL";
export const SEASON_UPDATE_RESET = "SEASON_UPDATE_RESET";

export const SEASON_DELETE_REQUEST = "SEASON_DELETE_REQUEST";
export const SEASON_DELETE_SUCCESS = "SEASON_DELETE_SUCCESS";
export const SEASON_DELETE_FAIL = "SEASON_DELETE_FAIL";

// Episodes of a season
export const EPISODE_LIST_BY_SEASON_REQUEST = "EPISODE_LIST_BY_SEASON_REQUEST";
export const EPISODE_LIST_BY_SEASON_SUCCESS = "EPISODE_LIST_BY_SEASON_SUCCESS";
export const EPISODE_LIST_BY_SEASON_FAIL = "EPISODE_LIST_BY_SEASON_FAIL";
