// List & details
export const SERIES_LIST_REQUEST = "SERIES_LIST_REQUEST";
export const SERIES_LIST_SUCCESS = "SERIES_LIST_SUCCESS";
export const SERIES_LIST_FAIL = "SERIES_LIST_FAIL";

export const SERIES_DETAILS_REQUEST = "SERIES_DETAILS_REQUEST";
export const SERIES_DETAILS_SUCCESS = "SERIES_DETAILS_SUCCESS";
export const SERIES_DETAILS_FAIL = "SERIES_DETAILS_FAIL";

export const SERIES_RANDOM_REQUEST = "SERIES_RANDOM_REQUEST";
export const SERIES_RANDOM_SUCCESS = "SERIES_RANDOM_SUCCESS";
export const SERIES_RANDOM_FAIL = "SERIES_RANDOM_FAIL";

// CRUD
export const SERIES_CREATE_REQUEST = "SERIES_CREATE_REQUEST";
export const SERIES_CREATE_SUCCESS = "SERIES_CREATE_SUCCESS";
export const SERIES_CREATE_FAIL = "SERIES_CREATE_FAIL";
export const SERIES_CREATE_RESET = "SERIES_CREATE_RESET";

export const SERIES_UPDATE_REQUEST = "SERIES_UPDATE_REQUEST";
export const SERIES_UPDATE_SUCCESS = "SERIES_UPDATE_SUCCESS";
export const SERIES_UPDATE_FAIL = "SERIES_UPDATE_FAIL";
export const SERIES_UPDATE_RESET = "SERIES_UPDATE_RESET";

export const SERIES_DELETE_REQUEST = "SERIES_DELETE_REQUEST";
export const SERIES_DELETE_SUCCESS = "SERIES_DELETE_SUCCESS";
export const SERIES_DELETE_FAIL = "SERIES_DELETE_FAIL";

// Summary
export const SERIES_SUMMARY_REQUEST = "SERIES_SUMMARY_REQUEST";
export const SERIES_SUMMARY_SUCCESS = "SERIES_SUMMARY_SUCCESS";
export const SERIES_SUMMARY_FAIL = "SERIES_SUMMARY_FAIL";

// Seasons of a series
export const SEASON_LIST_BY_SERIES_REQUEST = "SEASON_LIST_BY_SERIES_REQUEST";
export const SEASON_LIST_BY_SERIES_SUCCESS = "SEASON_LIST_BY_SERIES_SUCCESS";
export const SEASON_LIST_BY_SERIES_FAIL = "SEASON_LIST_BY_SERIES_FAIL";

export const SEASON_CREATE_REQUEST = "SEASON_CREATE_REQUEST";
export const SEASON_CREATE_SUCCESS = "SEASON_CREATE_SUCCESS";
export const SEASON_CREATE_FAIL = "SEASON_CREATE_FAIL";
export const SEASON_CREATE_RESET = "SEASON_CREATE_RESET";

export const CREATE_REVIEW_REQUEST = "CREATE_REVIEW_REQUEST";
export const CREATE_REVIEW_SUCCESS = "CREATE_REVIEW_SUCCESS";
export const CREATE_REVIEW_FAIL = "CREATE_REVIEW_FAIL";
export const CREATE_REVIEW_RESET = "CREATE_REVIEW_RESET";

export const DELETE_REVIEW_REQUEST = "DELETE_REVIEW_REQUEST";
export const DELETE_REVIEW_SUCCESS = "DELETE_REVIEW_SUCCESS";
export const DELETE_REVIEW_FAIL = "DELETE_REVIEW_FAIL";
export const DELETE_REVIEW_RESET = "DELETE_REVIEW_RESET";

export const SERIES_ADD_CAST = "SERIES_ADD_CAST";
export const SERIES_EDIT_CAST = "SERIES_EDIT_CAST";
export const SERIES_DELETE_CAST = "SERIES_DELETE_CAST";
export const SERIES_RESET_CAST = "SERIES_RESET_CAST";