export const CONTINUE_WATCHING_REQUEST = "CONTINUE_WATCHING_REQUEST";
export const CONTINUE_WATCHING_SUCCESS = "CONTINUE_WATCHING_SUCCESS";
export const CONTINUE_WATCHING_FAIL = "CONTINUE_WATCHING_FAIL";
export const CONTINUE_WATCHING_RESET = "CONTINUE_WATCHING_RESET";

export const DELETE_PLAYBACK_REQUEST = "DELETE_PLAYBACK_REQUEST";
export const DELETE_PLAYBACK_SUCCESS = "DELETE_PLAYBACK_SUCCESS";
export const DELETE_PLAYBACK_FAIL = "DELETE_PLAYBACK_FAIL";
export const DELETE_PLAYBACK_RESET = "DELETE_PLAYBACK_RESET";

export const CLEAR_ALL_PLAYBACK_REQUEST = "CLEAR_ALL_PLAYBACK_REQUEST";
export const CLEAR_ALL_PLAYBACK_SUCCESS = "CLEAR_ALL_PLAYBACK_SUCCESS";
export const CLEAR_ALL_PLAYBACK_FAIL = "CLEAR_ALL_PLAYBACK_FAIL";